from typing import Any, Dict, List

class binanceus:
    def __init__(self, config: Dict[str, Any]) -> None: ...
    def fetch_ticker(
        self, symbol: str, params: Dict[str, Any] = ...
    ) -> Dict[str, Any]: ...
    def fetch_order_book(
        self, symbol: str, limit: int = ..., params: Dict[str, Any] = ...
    ) -> Dict[str, Any]: ...
    def fetch_trades(
        self,
        symbol: str,
        since: int = ...,
        limit: int = ...,
        params: Dict[str, Any] = ...,
    ) -> List[Dict[str, Any]]: ...
