from typing import Any

class binanceus:
    def __init__(self, config: dict[str, Any]) -> None: ...
    def fetch_ticker(
        self, symbol: str, params: dict[str, Any] = ...
    ) -> dict[str, Any]: ...
    def fetch_order_book(
        self, symbol: str, limit: int = ..., params: dict[str, Any] = ...
    ) -> dict[str, Any]: ...
    def fetch_trades(
        self,
        symbol: str,
        since: int = ...,
        limit: int = ...,
        params: dict[str, Any] = ...,
    ) -> list[dict[str, Any]]: ...
