name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.0 flake8==7.0.0

      - name: Ruff (fail on issues)
        run: |
          ruff check .

      - name: Flake8 (critical errors only)
        run: |
          flake8 . --select=E9,F63,F7,F82 --show-source --statistics

# Notes:
# - We intentionally avoid running smoke tests here (they require a live backend).
# - If you want mypy later, add:
#   pip install mypy && mypy backend modules streamlit --ignore-missing-imports


